### ISSUE TITLE
Insufficent examples

### ISSUE THREAD

**Issue by raffaeler** [Azure/amqpnetlite#100]
I am familiar with the RabbitMQ dotnet client but there is no clear mapping of the amqpnetline APIs with the ones of the RabbitMQ client.

Specifically, I would suggest to re-create (where possible) the tutorials ([https://www.rabbitmq.com/getstarted.html](https://www.rabbitmq.com/getstarted.html) that are excellent to address the various queue patterns.

Also, I could not find any explanation about the API, its objects and methods.
If you expect this client would attract non-azure customers, you are wrong.

**Comment by robreeves** [comment]
@raffaeler It sounds like you are trying to take AMQP 0.9.1 knowledge and map it to this library, which is an AMQP 1.0 implementation. AMQP 1.0 is a complete rewrite of AMQP to the point that RabbitMQ considers it a completely different protocol in their own documentation. AMQP 1.0 is a much lower level protocol and does not define any architectures (brokers, queues, etc) like AMQP 0.9.1. AMQP 1.0 simply defines how to get a message from Node A to Node B in a reliable way. It just provides lower level building blocks to implement any messaging pattern that you want.

I generally agree with you that the project could use more extensive documentation and this would make it easier for those not familiar with the 1.0 AMQP spec to get started and accelerate the adoption of this library. However, if familiar with the 1.0 AMQP spec the library is fairly straightforward to use. The class names map almost perfectly to the specification and the entire public API has comments in the code. 

Since AMQP 1.0 does not define any architectures, I think a good solution would be to have a wiki showing how to implement common message patterns, like ZeroMQ (but much more concise than the ZeroMQ documentation!) http://zguide.zeromq.org/page:all. A few of the patterns exist in the example section https://github.com/Azure/amqpnetlite/tree/master/Examples, but putting it in a wiki makes it more consumable for someone looking at the project for the first time.

By the way, I am a non-azure customer using the library. Why? Because you won't find many, if any, AMQP 1.0 (not 0.9.1.) .NET implementations that are as concise and simple as this library.

**Comment by raffaeler** [comment]
Thank you for your answer, Rob.
I am aware of the (very sad) differences between AMQP 1.0 and 0.9.
Anyway, I believe a client library should show some form of interop with the most common implementations like rabbit, zeromq, etc.
From this side, rabbitmq published some documentation about the mapping between the two protocols. There is no code but I figured out how to make a amqp 1.0 client to "talk" with another amqp 0.9 client.
BTW, when I mean API docs, I mean that the Trace object was not obvious to find, and it was the only way to understand why it was failing.

**Comment by robreeves** [comment]
@raffaeler Ah, okay. My misunderstanding on the API comments. Whenever I use tracing, I always set it to TraceLevel.Frame. Everything you see there seems to map directly to the performatives defined in section 2.7 of the spec from what I can tell. For example:

> [09:23.712] SEND (ch=0) open(container-id:ContainerHost-fa1d6d65f7324fb3b7c327f7
> 699f6344,host-name:myhostname,max-frame-size:262144,channel-max:7)

Maps to:

```
<type name="open" class="composite" source="list" provides="frame">
    <descriptor name="amqp:open:list" code="0x00000000:0x00000010"/>
    <field name="container-id" type="string" mandatory="true"/>
    <field name="hostname" type="string"/>
    <field name="max-frame-size" type="uint" default="4294967295"/>
    <field name="channel-max" type="ushort" default="65535"/>
    <field name="idle-time-out" type="milliseconds"/>
    <field name="outgoing-locales" type="ietf-language-tag" multiple="true"/>
    <field name="incoming-locales" type="ietf-language-tag" multiple="true"/>
    <field name="offered-capabilities" type="symbol" multiple="true"/>
    <field name="desired-capabilities" type="symbol" multiple="true"/>
    <field name="properties" type="fields"/>
</type>
```
Hope that helps a little :)

**Comment by raffaeler** [comment]
It would have helped before :)
But thank you anyway!

**Comment by xinchen10** [comment]
I agree the APIs need to be better documented. The plan was to make the code comment XML accessible through web pages or readme files and keep improving the code comments. Today we have decent amount of examples, including Azure specific ones and those that work with general AMQP 1.0 brokers. However, without reading the code it is not easy to find relevant examples. We also have some information in the wiki pages. For example, the [Tracing ](https://github.com/Azure/amqpnetlite/wiki/Tracing) page describes how to enable tracing in the library. You both mentioned the getting-started page from other projects and I think that is the first thing we will improve here.

**Comment by raffaeler** [comment]
Please consider using DocFX [https://dotnet.github.io/docfx/](https://dotnet.github.io/docfx/)
Samples are useful when target a single feature in few lines of code.
IMO the rabbitmq tutorials are excellent for their purposes.
I expect a lot of people not even reading the AMQP 1.0 specs, wants to quickly start with some working code to evaluate if its is worth to spend more time or drop the project.
