### ISSUE TITLE
DNXCore,Version=v5.0

### ISSUE THREAD

**Issue by JimmyHurrah** [Azure/amqpnetlite#104]
My understanding was that amqpnetlite would work in projects targeting framework `dnxcore50` 
When I install the package `dnu install amqpnetlite` and build my project `dnu build --framework dnxcore50` it gives me an error: 

> The dependency AMQPNetLite 1.1.6 in project X does not support framework DNXCore,Version=v5.0.

Is there someting I missed or missunderstood?

**Comment by xinchen10** [comment]
DNX targets are not available in the NuGet package. The assemblies are available only from local build. From the solution directory, you can run `dnu restore dnx\Amqp.DotNet` and `dnu build dnx\Amqp.DotNet`. The binaries can be found in the target folder under dnx\Amqp.DotNet\bin\Debug. It is not included in the NuGet package because coreclr is still changing and we haven't done enough validation on this platform. Thanks.

**Comment by JimmyHurrah** [comment]
Ah that makes sense. Thanks for your help!
