### ISSUE TITLE
Link OnAttached is not called, unless both a target and source are present

### ISSUE THREAD

**Issue by robreeves** [Azure/amqpnetlite#110]
For a client sender link, only a target is required. For a client receiver link, only a source is required. The OnAttached delegate will only get called if both fields are present. This means OnAttached is not called for:

    new ReceiverLink(sess, linkname, new Attach() { Source = new Source() { Address = sourceAddr }, (l, a) => //do stuff);

    new SenderLink(sess, linkname, new Attach() { Target = new Target() { Address = targetAddr }, (l, a) => //do stuff);

This is because of this check in Amqp.Link.OnAttach:

        if (this.onAttached != null && attach.Target != null && attach.Source != null)
        {
            this.onAttached(this, attach);
        }

The workaround for now is to always include a target and source object in the attach object.

**Comment by xinchen10** [comment]
A link must have source and target set. A sender link without source will never produce outgoing messages and a receiver link without target will never permit incoming messages (section 2.7.3). They can be empty unless special values are required (e.g. in request/response case the receiver's target should have an address for reply-to messages).

The library is not enforcing this rule now. But instead of enforcing it, I am going to remove the source and target null check in OnAttach. The application may want to look at the attach command anyway.
