### ISSUE TITLE
AMQP.Net with DNX/.Net core support

### ISSUE THREAD

**Issue by kant2002** [Azure/amqpnetlite#112]
Could you publish NuGet package with support for .NET Core/DNX?

**Comment by xinchen10** [comment]
Last time I checked, the SslStream async read/write issues were not fixed in corefx. Without that this amqps transport is not working.

**Comment by kant2002** [comment]
Maybe it make sense publish it as preview, how it was done for Azure Storage library. At least it could be usable for non-SSL protocols.

**Comment by martinnormark** [comment]
Has v1.1.9-rc tag been pushed to Nu Get? The nuspec file was updated, but Nu Get still only has 1.1.8 - will the pre-release of 1.1.9 be pushed?

**Comment by xinchen10** [comment]
I just pushed the package to NuGet. My original plan was not publishing it and instead asking people to download from GitHub release and reference the local downloaded package. The reason is that if I want to do a stable release of 1.1.9 before .Net Core RTM I would have to remove the netstandard target from the package because it depends on pre-release corefx packages. However, this makes it inconvenient for people to try it out. The package should be available on NuGet now.
