### ISSUE TITLE
Message Body string serialization

### ISSUE THREAD

**Issue by maiorfi** [Azure/amqpnetlite#117]
Hi.

In a sample I developed using .NETMF flavor of your (amazing) library, I send periodically messages with following code:

```csharp
while (true)
            {
                var counter = Interlocked.Increment(ref _messageCounter);

                Debug.Print("Sending Message #" + counter + "...");

                _led0.Write(true);

                lock (_senderLocker)
                {
                    _sender.Send(new Message
                    {
                        Body = "Message #" + counter
                    }); 
                }

                _led0.Write(false);

                Debug.Print("...done");

                Thread.Sleep(5000);
            }
```

On Receiver side (e.g. using DeviceExplorer or ServiceBusExplorer tools) I get a couple of "junk" bytes just before that UTF8-encoded ones...could it be related to a mismatch between sender serialization and receiver deserialization?

Thanks!

**Comment by robreeves** [comment]
Can you give an example of the exact string you send and the junk bytes that you receive that precede the UTF8 bytes? My suspicion is that you are looking at the AMQP serialized bytes, which include information about the type that you are sending. For example sending "hello world" would include the type encoding 0xa1 and then the length.

161, 11, ...UTF8 bytes for "hello world"...

Check out the "Type: string" section on p. 18 here http://www.amqp.org/sites/amqp.org/files/amqp.pdf

**Comment by xinchen10** [comment]
@maiorfi this is a mismatch in client library APIs. AMQP defines three message body types: value, data and sequence. Most of the time the first two are used. When you create a message with body set to a .Net object, the amqpnetlite library encodes it into an AMQP Value message. The object is encoded as [format-code] [type-specific bytes in AMQP type system]. However, the Iot and Service Bus clients have their own model to expose the underlying AMQP message. For example, EventData only provides the body as a byte array. For a Value message, all bytes are returned including the [format-code], because without the [format-code] there is no way to decode the original object.

If you use an AMQP client (without wrappers) on the receiver side, you should be able to have access to the message body and get correct object back.

To make it work, you would need to send raw bytes using the Data message type. 
```
_sender.Send(new Message
    {
        BodySection = new Data() { Binary = Encoding.UTF8.GetBytes("Message #" + counter)}
    }); 
```

**Comment by xinchen10** [comment]
@maiorfi I am not sure if you are using the Micro version on NETMF. That one does not support setting different type of body sections. I will fix it so user has more control on the body.

**Comment by maiorfi** [comment]
@xinchen10 Great, thanks!
