### ISSUE TITLE
Using AMQP .Net Lite with .Net Core 1.0

### ISSUE THREAD

**Issue by ppatierno** [Azure/amqpnetlite#125]
I'm trying to use AMQP .Net Lite with .Net Core 1.0 under RHEL and Ubuntu.
I see that the Nuget package provides netcore451 but in the source code we have dnxcore50 which compiles great with .Net Core 1.0 on RHEL.
Trying to use the netcore451 package I receive an error about Windows runtime assemblies not available (of course !).
What's the right way to use (if possible as it seems to be) the AMQP .Net Lite under Linux with .Net Core 1.0 ?

**Comment by xinchen10** [comment]
dnxcore50 is not included in the NuGet package yet. The current netcore451 target is for Windows 8.1, Windows Phone 8.1 and UWP. It seems that the new .Net Core 1.0 framework moniker has changed again, and that may need some update in the code.

**Comment by ppatierno** [comment]
Did you try to use it under Linux ? I'm using RHEL 7.2 and the build always tries to get AMQP .Net Lite from Nuget but the 1.1.9-rc isn't define. How can I use the assembly build locally from the source code ? You defined it as dependency in the project.json of HelloAmqp but compiler search it always on Nuget.

**Comment by ppatierno** [comment]
I'm able to run HelloAmqp using the dependency : 

"Amqp": "1.1.9-*"

instead of : 

"AmqpNetLite": "1.1.9-rc"

**Comment by MaherJendoubi** [comment]
@ppatierno Would you please share your project.json?

**Comment by xinchen10** [comment]
@ppatierno 1.1.9-rc was not pushed to NuGet yet. By changing the dependency you are doing a project reference directly instead of NuGet package. That works for the HelloAMQP example because it is located under the same parent directory as the Amqp project. It may not work if you create a sample in another location.

I just pushed the package to NuGet, so the sample should work as is.
