### ISSUE TITLE
A question on how to implement flow control on the server

### ISSUE THREAD

**Issue by perfectphase** [Azure/amqpnetlite#130]
Hi, I was wondering if you could point me in the direction of the best sample that would help me with my problem.

I have a server and a client connected over amqp using amqpnetlite, both are under my control, source wise. The situation I have is the client sends a request which results in the server sending n response messages. In a certain use case this results in the server having to send ~50,000 messages to the client.

At the moment I'm using IRequestProcessor and using requestContext.ResponseLink.SendMessage to send the bulk of the response messages, but I'm seeing the server get overwhelmed as it generates the messages far faster than the client can receive and throws an out of memory exception (this is compiled as x86)

So I'd like to implement some form of back pressure to throttle the rate I call SendMessage on the response link, I understand that amqp has link credit, but what I really want to do is control the size of the buffer used in the server.

Does that make any sense, anyone able to point me in the right direction?

Cheers,

Stephen.

**Comment by xinchen10** [comment]
@perfectphase it is not common to have 50000 response messages for one request, at least the request processor model in the library is not designed for such cases. But you can still make your scenario work by using the features offered by the library.

Option 1: implement paging using IRequestProcessor. Client and server can use some bookmark or continuation token to break the response stream into multiple pages. Server now can load the messages for a given page and push them to the client.

Option 2: You could model your response messages for a given request as a conceptual or virtual queue. In this case you can use ILinkProcessor and IMessageSource to serve client requests. Each client request is modeled as a link and the attach request carries the necessary information. Your ILinkProcessor implementation now can inspect the attach command and create a SourceLinkEndpoint that wraps an IMessageSource. In IMessageSource implementation you can load messages on demand (or have a predefined memory buffer to improve performance). Since IMessageSource.GetMessageAsync is called when credits are received from the client, you will not run into memory issue due to buffered messages. There are examples showing how to use IMessageSource and SourceLinkEndpoint.

Let me know if you run into any issues.

Regards,
Xin

**Comment by xinchen10** [comment]
Please reopen the issue or open new ones if you have other questions.
