### ISSUE TITLE
sending messages to event hub on .net core

### ISSUE THREAD

**Issue by caserzer** [Azure/amqpnetlite#141]
I have a scenario that will send messages to event hub using .net core applications. In this scenario the RPS will be about 10K RPS, so I doing some test using the amqp lite . I only can send 100 messages in 6 seconds, although I can send messages in different sessions, but that will be much far away from my target. Any suggestion ?

**Comment by robreeves** [comment]
Event Hubs only allows 1000 messages/sec/throughput unit. Sending 10,000 messages per second could be expensive without batching. Is it possible to batch the data up into fewer messages? 

You can also send messages in a batch to an Event Hub to minimize the round trips, but I'm not sure exactly how the batch of messages is formatted into a single AMQP message under the hood. This will cut down the round trips over the network, but not the number of messages per second so you'll still need a lot of throughput units.

**Comment by caserzer** [comment]
- I did not find the AMQP Lite SendBatch API , according to the code, I think it will not support the batch.
- I test one connection , 10 session , the sending speed is about 125 RPS
- switch to the IOT hub using MQTT sounds like an option ?

**Comment by xinchen10** [comment]
I think you are doing synchronous send in a loop. It is expected to be slow, because you are sending one message at a time. Assuming each message takes 20ms (which is excellent for a cloud messaging service), you can only get 50 rps for a given sender link. A simple way to get higher throughput is to send messages asynchronously - call Send and handle the outcome from a callback or a task continuation. This way the Send call is non-blocking and you can send the message as soon as it is available. You can take a look at the `PerfTest` project to see how this works. This will give you 1000+ RPS easily from a single sender link. If you need more, create another connection/session/link. You can run the `PerfTest` tool against your event hub and see what you can get.

SendBatch is not really required to achieve high throughput. `await sender.SendBatchAsync(Message[])` can be equally done with `await Task.WhenAll(messages.Select(m => sender.SendAsync(m)))`.

**Comment by caserzer** [comment]
Thanks @xinchen10 . Although I still cannot get the RPS to the 1K per throughput unit . But this way is much faster and meet the target.
