### ISSUE TITLE
Issues while using sessions on .Net Core

### ISSUE THREAD

**Issue by samirski** [Azure/amqpnetlite#146]
I might be missing something as I just started using this library, but whenever I try to use the session functionality on a queue using .Net Core I'm not getting the expected behavior. First of all I can't get a session filter to work while receiving from a partitioned queue. Secondly while running a receiver in a loop I can only get one message at a time on an open connection. Again this might be something that I'm missing here. I would greatly appreciate any help on these issues. 

Forgot to mention that I'm using Azure Service Bus services and the logic is based on MessageSessionExample implementation.

**Comment by xinchen10** [comment]
@samirski does the session filter work for you with a non-partitioned queue (you would need to create the queue using the SDK by setting EnablePartitioning to false)? Can you explain more about the second issue? By design the ReceiverLink.Receive API returns one message. It is expected that the application calls Receive in a loop to process messages when they become available.

**Comment by samirski** [comment]
@xinchen10 yes, it work on a non-partitioned queue. And what I meant about getting one message at a time is this.

The following code will get only one message from a queue:

`...
Connection connection = new Connection(this.GetAddress());
 Session session = new Session(connection);
Map filters = new Map();
filters.Add(new Symbol("com.microsoft:session-filter"), sessionId);

                ReceiverLink receiver = new ReceiverLink(
                session,
                "sessionful-receiver-link",
                new Source() { Address = this.Entity, FilterSet = filters },
                null);

            for (int i = 0; i < count; i++)
            {
                Message message = receiver.Receive(30000);
                if (message == null)
                {
                    break;
                }
                receiver.Accept(message);
            }

            receiver.Close();
            session.Close();
            connection.Close();`


This one will get all of the available messages from the queue based on the provided count variable:

`...
            for (int i = 0; i < count; i++)
            {
               Connection connection = new Connection(this.GetAddress());
               Session session = new Session(connection);
               Map filters = new Map();
               filters.Add(new Symbol("com.microsoft:session-filter"), sessionId);

                ReceiverLink receiver = new ReceiverLink(
                session,
                "sessionful-receiver-link",
                new Source() { Address = this.Entity, FilterSet = filters },
                null);

                Message message = receiver.Receive(1000);
                if (message == null)
                {
                    break;
                }
                receiver.Accept(message);

                receiver.Close();
                session.Close();
                connection.Close();
            }
`

**Comment by xinchen10** [comment]
@samirski I have asked the team who owns the Service Bus queue to take a look at the partitioned queue issue. For now can you enable frame tracing and share the output (remove the sasl-init frame which may contain your credentials)? Instructions for enabling tracing is here (you may want to output to Console instead of debug trace):
http://azure.github.io/amqpnetlite/articles/tracing.html

**Comment by samirski** [comment]
@xinchen10 Sure, I'll do that tonight when I'm back home. Btw have you had a chance to look that the second issue I've reported? This is actually is more important I think as otherwise there is no way to implement the request/response pattern properly.

**Comment by samirski** [comment]
@xinchen10 As promised I'm attaching a file with the frame tracing enabled.

[Frame tracing on a partitioned queue.txt](https://github.com/Azure/amqpnetlite/files/387586/Frame.tracing.on.a.partitioned.queue.txt)

Also I've tested the the same code (MessageSessionExample.cs) on a non-partitioned queue and this time while reading the data from that queue without specifying the session id (being set to null) I'm getting 34 messages at a time. The for loop counter is being set to 1000 and there are close to 150 messages in the queue. Why I'm getting only a certain number of messages on an open connection I have no idea. Btw just in case I've updated the code and don't break if the message is null, to make sure that on the next iteration I'm still not getting anything.

**Comment by xinchen10** [comment]
With partitioned queue, the link attachment fails (as you can see in the trace). This is the issue we are investigating.

For the non-partitioned queue case, do all your messages have the same SessionId (group-id of AMQP message)? When you specify a null session id in the filter, the service returns the first available session and the messages from that session. Messages from other sessions are not delivered.

**Comment by samirski** [comment]
@xinchen10 Thanks for an update. Speaking of the null session id, I thought that is the way to received the messages from the queue regardless the session id used by the sender. If this behavior is by design, how to to know in that case that there are messages with a different session id? Do we suppose to disconnect and connect again? This will work but the performance will suffer greatly and what's more important as long as there are messages to receive for an acquired session id (first available), the messages with a different session id will never be received.

**Comment by brvaland** [comment]
@samirski did you manage to find a solution as i am facing the same issue with session id null?

**Comment by xinchen10** [comment]
Each session must be acquired by attaching a link with the session filter. A null session id in the filter matches any available session on the broker but it only acquires that session. The acquired session id is sent in the attach frame (session id filter) from the broker. If you need to process other sessions, you would need to create new links. @samirski is right that the performance will suffer if you have very few messages in all sessions. In general this should not be an issue because attaching a link is relatively fast when the connection is established. Also if each session has only one or two messages, the application may not be using sessions in the right way.

Session lifetime is controlled by application. For example, a work flow may have an activation message first and a completion message last. When the completion message is seen, the session (link) can be closed.

The issue with partitioned entity is caused by a bug in the service. The fix should be available soon.

**Comment by brvaland** [comment]
@xinchen10 - Can you please share an example code on how to go about creating a new link ? I would like to cleanly check there are no further messages for the session and create new a session id filter that is will be available when null session id is passed.

**Comment by xinchen10** [comment]
Sessions with partitioned entity should work now.

Session boundary is determined by the application, for example using an end-of-session message. When you receive this message, close the link and open a new one to acquire a new session. More details can be found here: https://github.com/Azure-Samples/azure-servicebus-messaging-samples/tree/master/Sessions
