### ISSUE TITLE
Creation of service bus nodes

### ISSUE THREAD

**Issue by herecydev** [Azure/amqpnetlite#153]
I've been struggling with the service bus examples, though I'm certain the address is correct. Am I right in thinking that the "myEntity" is an **existing** queue/topic that the library is publishing to. And if so, is there a way to programmatically create service bus entities that will work on `netcore`.

**Comment by xinchen10** [comment]
Yes, "myEntity" is the name of an existing queue/topic the app is trying to publish to. Since management is not within the AMQP spec, the app has to provision the entity using the broker specific tool or protocol. For the Service Bus, there is no SDK for management APIs currently on .Net Core. If you do not want to create the queue/topic from the Azure portal, you would need to implement the REST protocol specified here https://msdn.microsoft.com/en-us/library/azure/hh780776.aspx.

**Comment by herecydev** [comment]
Thanks, that's exactly what I expected. I would suggest updating the docs to indicate that their is a dependency on an entity being created first with the matching name.
