### ISSUE TITLE
AMQP.AMQPException on UWP App with V1.20 of AMQP.NetLite

### ISSUE THREAD

**Issue by barnstee** [Azure/amqpnetlite#154]
This issue doesn't Repro with V1.18, so it appears to be a regression in V1.20:

The AMQP Connection (to Azure IoT Hub) appears to be closed under the covers. I then get:
Exception thrown: 'Amqp.AmqpException' in Amqp.NetCore.dll
Additional information: Operation 'Send' is not valid under state: DetachSent.
10:27:24.452 RECEIVED VALUE[1] Value=09/16/2016 08:27:24
10:27:24.520 QUEUE VALUE[1]: Value=09/16/2016 08:27:24 CODE=0<00000000> OVERFLOW=False
Exception thrown: 'Amqp.AmqpException' in Amqp.NetCore.dll
Additional information: Operation 'Close' is not valid under state: EndSent.
10:27:24.452 IsReadyToPublish[1] NORMAL
Exception thrown: 'Amqp.AmqpException' in mscorlib.ni.dll
Additional information: Operation 'Close' is not valid under state: EndSent.
Exception thrown: 'System.InvalidOperationException' in mscorlib.ni.dll
Additional information: An attempt was made to transition a task to a final state when it had already completed.
Exception thrown: 'Amqp.AmqpException' in mscorlib.ni.dll
Additional information: Operation 'Close' is not valid under state: EndSent.

After that, await factory.CreateAsync() with a new factory object never returns.

Any idea?

**Comment by barnstee** [comment]
Correction, not a regression: I managed to repro on V1.18 as well and it seems to be related to unreliable TCP/IP connections (it repros with my cell phone as personal hotspot in less than 5 minutes).

**Comment by xinchen10** [comment]
When the tcp connection is closed, it is expected to get AmqpException from Send or Close calls. But the InvalidOperationException on task completion and factory.CreateAsync hang are unexpected. Can you share your code so I can try it out?

**Comment by barnstee** [comment]
Thanks for the quick repose!
Here is the code: https://github.com/OPCFoundation/UA-.NETStandardLibrary
Just clone and open the solution, making https://github.com/OPCFoundation/UA-.NETStandardLibrary/tree/master/SampleApplications/Samples/Publisher the default project, update the AMQP.NetLite NuGet package back to V1.20 (I had to revert back to V1.18 to unblock us, as V1.18 runs reliable after all) and run the app in a debugger.
The questions are:
1. Why does the AMQP/TCP connection die?
2. Why does factory.CreateAsync() hang?
Thanks for your help!

**Comment by xinchen10** [comment]
@barnstee I have been looking at the Publisher sample under the prototyping branch. Let me know if that's not the right place.

Are you using the AmqpConnection class directly or any derived class from it? What's the expected behavior of the AmqpConnection class in terms of error handling and reconnect? Looking at the code, I think the contract is that the caller creates the object, calls OpenAsync once, and then keeps calling Publish. The AmqpConnection class should recover from exceptions and send all message in the queue. Is that correct?

But I am not sure about the above because in Publish there is a check for IsClosed which returns true when the underlying amqp connection is closed (the flag is set in the closed callback).

I couldn't get the sample running as is due to the missing configuration, so I am trying to take the AmqpConnection class and use it in a standalone test.

**Comment by barnstee** [comment]
@xinchen10, you got it.
I'll send you my config file for Azure IoT Hub privately, so you can run the sample without modifying it.

**Comment by xinchen10** [comment]
@barnstee I finally got the Publisher sample working. There is a bug in v1.2.0 in the uwp lib. I will update you once I have a fix for it.

**Comment by xinchen10** [comment]
Please try v1.2.1.
