### ISSUE TITLE
Message lock problem in .net core

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [Azure/amqpnetlite#168]
I have noticed an issue with the library regarding message locking.

Consider the following...

`

    if (this.receiverLink == null)
    {
        this.receiverLink = new Amqp.ReceiverLink(this.session, "receiver-link", subscriptionPath);
    }

    for(;;)
    {
        var message = await this.receiverLink.ReceiveAsync(5000);

        if (message != null)
        {
            // Process message

            await Task.Delay(2000);

            this.receiverLink.Accept(message);
        }
    }
`

In the code above we are just taking a message every two seconds.  We notice that each subsequent message has a lock expire time that is in some cases identical or at least within fractions of a second.  For example:

message1 lock expire: 2016-11-03T21:41:04.438Z
message2 lock expire: 2016-11-03T21:41:04.438Z
message3 lock expire: 2016-11-03T21:41:04.501Z

I would expect that the lock expire would advance each time ~2s unless the library is taking more than one message at a time under the covers.
The problem with the code above is that after 30 messages for example and having lock duration of 1 minute the bus will stop honoring the call to Accept() the message causing it to be re-enqueued on the subscription.

I have thought to renew the lock but there doesn't appear to be a way to do that through this library.

**Comment by xinchen10** [comment]
This is the default behavior of the client (or AMQP). The receiver works in a prefetch mode (or the AMQP term link credit). It is set to 200 by default in the client. Assuming you have enough messages in the queue, the client tries its best to keep 200 messages in the local buffer waiting for the application to dequeue. If message processing is time consuming, the application should reduce this link credit (or prefetch count) so that messages can be processed in time. In the extreme case, the application can set this number to 1, so it will get one message from the server at a time and not have the lock timeout issue.

To set the link credit, call the SetCredit method after the receiver link is created.
```
this.receiverLink = new Amqp.ReceiverLink(this.session, "receiver-link", subscriptionPath);
this.receiverLink.SetCredit(1);
```

Smaller number will hurt performance, so it is tradeoff that the application has to make.

The Service Bus supports renewing the message lock but its a layered protocol on top of AMQP. This library does not support it.

**Comment by Blackbaud-DanHamlin** [comment]
Thank you for the prompt response. I had searched the repo for prefetch but wasn't aware of the link credit lingo.
