### ISSUE TITLE
Message encoding does not work correctly

### ISSUE THREAD

**Issue by Marcel-Lambacher** [Azure/amqpnetlite#177]
I'm using the newest version of this lib.
The server is ActiveMQ, also in the newest version.

Here's an example how I send messages:

 ```
var msg = new Message("1 ä 1 ü 1 ö");
_senderLink.Send(msg, TimeOutInMilliseconds);
```

The message will delivery correctly, but something is wrong with the encoding.
If I'm reading the message with **any** other clients, the result will be this:
`Sw¡1 Ã¤ 1 Ã¼ 1 Ã¶`

For testing I've tried to encode the message manually.

UTF8:
```
var encodedMessage = Encoding.UTF8.GetBytes("1 ä 1 ü 1 ö");
var msg = new Message(encodedMessage);
```

Result is: `Sw 1 Ã¤ 1 Ã¼ 1 Ã¶`

UTF32:
```
var encodedMessage = Encoding.UTF8.GetBytes("1 ä 1 ü 1 ö");
var msg = new Message(encodedMessage);
```

Result is: `Sw ,1 ä 1 ü 1 ö`

Unicode:
```
var encodedMessage = Encoding.Unicode.GetBytes("1 ä 1 ü 1 ö");
var msg = new Message(encodedMessage);
```

Result is: `Sw 1 ä 1 ü 1 ö`

If I'm just use amqpnetlite to amqpnetlite, the encoding is fine.
What's the problem here?

**Comment by xinchen10** [comment]
@Marcel-Lambacher what other clients you used to read the messages?

When you create a message with an object, the AMQP message body is set to AMQP Value. In your case the first message has an AMQP Value body of a string, and other three have an AMQP Value body of binary. When encoded, the body section contains the special bytes for AMQP Value, followed by the bytes for the encoded object.

Some clients by default treats the entire body section as opaque bytes. That will create the problem you are seeing. The extra protocol encoding is also included at the beginning of the payload.

To work with those clients, you can send the message as AMQP Data message (body is of type Data, instead of AMQP Value).
```
var message = new Message() { BodySection = new Data() { Binary = System.Text.Encoding.UTF8.GetBytes("1 ä 1 ü 1 ö") } };
```

**Comment by Marcel-Lambacher** [comment]
I'm using the Webinterface from ActiveMQ, I've also tried the Java JMS client. Both clients have the same behaviour. On the Java JMS site, the message will be received as  a bytes message. This explains why the encoding isn't working correctly. But why the messages are received as bytes message and not as text message as expected?

 I've also tried your solution:
`var message = new Message() { BodySection = new Data() { Binary = System.Text.Encoding.UTF8.GetBytes("1 ä 1 ü 1 ö") } };`

This isn't working too.

**Comment by xinchen10** [comment]
@Marcel-Lambacher I assumed your JMS receiver also uses the AMQP protocol, but my assumption may be wrong. Most likely you are sending the message through AMQP via amqpnetlite, but receiving the message through some other protocol via the JMS API. Due to the different protocols, there is a message conversion inside the ActiveMQ broker.

According to this page (https://activemq.apache.org/amqp.html) (strategies under the Mapping to JMS section), the AMQP message is converted to a BytesMessage for a JMS consumer that does not use the AMQP protocol. Note that the jms strategy does separate the headers and the body, but I am not sure if the body includes protocol encoding or just the payload itself. If the latter, your scenario might work but I haven't confirmed that.

If possible, I would recommend you use AMQP for the consumer too. You can still use the JMS API but specify AMQP as the underlying transport. I believe in this case the message is delivered without conversion. I tested the following code with ActiveMQ 5.14.3. The received message is a TextMessage and the body is handled correctly.
```
import java.util.Hashtable;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.Destination;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.naming.Context;

public class Test {
    public static void main(String[] args) throws Exception {
        Hashtable<Object, Object> env = new Hashtable<>();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "org.apache.qpid.jms.jndi.JmsInitialContextFactory");
        env.put("connectionfactory.myFactoryLookup", "amqp://localhost:5672?jms.username=admin&jms.password=admin");
        Context context = new javax.naming.InitialContext(env);

        ConnectionFactory connectionFactory = (ConnectionFactory)context.lookup("myFactoryLookup");
        Connection connection = connectionFactory.createConnection();
        connection.start();
        Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
        Destination destination = session.createQueue("q1");
        MessageConsumer consumer = session.createConsumer(destination);

        Message message = consumer.receive(60000);

        if (message instanceof TextMessage) {
            TextMessage textMessage = (TextMessage) message;
            String text = textMessage.getText();
            System.out.println("Received: " + text);
        } else {
            System.out.println("Received: " + message);
        }

        consumer.close();
        session.close();
        connection.close();
    }
}
```

This code is using the Qpid JMS client.
```
        <dependency>
          <groupId>org.apache.qpid</groupId>
          <artifactId>qpid-jms-client</artifactId>
          <version>0.11.1</version>
        </dependency>
```
