### ISSUE TITLE
SSL option is missing in IoT Core project

### ISSUE THREAD

**Issue by tgabee2** [Azure/amqpnetlite#178]
I've added AMQPNetLite package to a Windows IoT Core project, and the basic functions work well. But it seems the ConnectionFactory object does not have SSL field, so SSL option cannot be set.
How it is possible to use SSL in IoT projects?

**Comment by xinchen10** [comment]
@tgabee2 Do you mean enabling SSL or configuring SSL? If the address scheme is "amqps" the library uses SSL. The IoT Core project references the netcore451 lib which implements SSL using WinRT StreamSocket. Most of the SslSettings properties are not applicable to that class, so it is not available on ConnectionFactory.

If you are building uap10 app and really need to control SSL settings, you might be able to reference the netstandard1.3 target. This is my understanding after reading the netstandard documents but I haven't verified it. You would need to build the current master to get the package as the standalone netstandard1.3 package is not released yet.

**Comment by tgabee2** [comment]
Thanks for the reply.

My basic problem is using SSL without SSLSettings. Without the settings I cannot set the certificate on client side, and so on. Like this the server does not accept the connection.
I try to create a connection without any SSL setting and simply use amqps in address, the server not started because it doesn't find the certificate (exception in Amqp.Listener.ConnectionListener.GetServiceCertificate()). I don't find any example using SSL without settings. Could you provide me a simple one? 
I also don't find a way to reference the netstandard1.3 as you suggested. Could you explain it a bit more?

Thank in advance!

**Comment by xinchen10** [comment]
@tgabee2 do you need SslSettings for your IoT Core client only?

It seems that UWP does not completely support netstandard1.3 yet. For example, System.Threading is not working https://github.com/dotnet/corefx/issues/2576. So right now we cannot use the netstandard1.3 lib for UWP yet.

Right now this library has one target (netcore451) that can be consumed by uap10, windows 8.1 and windows phone 8.1 projects. Because the portable profile choice, it cannot use some APIs such as StreamSocket.Control.ClientCertificate. One way to fix this is to create a new project targeting uap10 so we can expose more controls on the underlying socket.

**Comment by tgabee2** [comment]
Yes. My goal is to implement an AMQP server in a standard Windows Service (with .NET Framework 4.6.2) and  a client in an UWP app running on Windows IoT Core (on a Raspberry Pi3 device).
Server works well, but on client side I have the described issues.

Thank you for the support!
