### ISSUE TITLE
Occasional slowness sending to Azure Service Bus Queue/Topics

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/amqpnetlite#199]
I'm seeing some occasional slowness when sending to an Azure Service Bus queue or topic. This is causing my ASP.NET Core site to have very lengthy response times. The behavior isn't consistent that I can tell.

Some traces on a production server at Azure show the following POSTs:

![image](https://cloud.githubusercontent.com/assets/351190/23824043/61faa0cc-063d-11e7-8ff8-9918de9bd165.png)

`AmqpClient` is a helper class I wrote that is registered as a singleton in the ASP.NET Core DI container. This is done to reuse the connection object. The class's code is below. It is registered with `services.AddSingleton<AmqpClient>();`:

```c#
    namespace Infrastructure
    {
        using System;
        using System.Threading.Tasks;

        using Microsoft.Extensions.Configuration;
        using Microsoft.Extensions.Logging;

        using Amqp;

        /// <summary>
        /// This class should be kept around as a singleton so we're not disposing of the connection.
        /// </summary>
        public class AmqpClient : IDisposable
        {
            private readonly string address;
            private Lazy<Connection> connection;
            private object connectionLock = new object();

            public AmqpClient(IConfigurationRoot configuration)
            {
                this.address = configuration.GetConnectionString("AzureServiceBus");
                this.connection = this.CreateConnection();
            }

            public async Task SendAsync(Message message, string entityPath)
            {
                if (this.connection.Value.IsClosed)
                {
                    lock (this.connectionLock)
                    {
                        if (this.connection.Value.IsClosed)
                        {
                            // Recreate connection
                            this.logger.LogInformation("Recreating connection");
                            this.connection = this.CreateConnection();
                        }
                    }
                }

                var session = new Session(this.connection.Value);
                var senderLink = new SenderLink(session, "send-link/" + entityPath, entityPath);

                try
                {
                    await senderLink.SendAsync(message);
                }
                finally
                {
                    await senderLink.CloseAsync();
                    await session.CloseAsync();
                }
            }

            public void Dispose()
            {
               this.logger.LogInformation("AmqpClient Dispose()");
                Dispose(true);
                GC.SuppressFinalize(this);
            }

            protected virtual void Dispose(bool disposing)
            {
                if (disposing)
                {
                    this.connection.Value.Close();
                }
            }

            private Lazy<Connection> CreateConnection()
            {
                return new Lazy<Connection>(() => new Connection(new Address(this.address)));
            }
        }
    }
```

When the response time increases the app's thread count and handle count grows. I don't know if the thread-count or handle growth is internal to my AMQP code or just server threads being created to handle the additional requests due to the slowness of sending a message.

Is keeping the Connection object around forever a bad idea? From what I've read here, it seems like the right thing to do. I know it is expensive to create. I had a previous version of this code that cached the `senderLink` and `session` objects as well, but it also had the same issues so I simplified it to the above code in hopes that would solve the problems.

What's interesting is that I have this app on multiple instances at Azure and they often slow down at the same time, which leads me to think that there's a problem with keeping multiple connections open as long as I am since they are all created at the same time.

**Comment by xinchen10** [comment]
@BrianVallelunga have you eliminated the possibility that the server was slow at that time?

How often do you call SendAsync? If it is more than 10 times per second, I would recommend also keep the link.

You are using the constructor to create the connection, which is not recommended in a service component, because underneath it creates the tcp socket and opens the ampq connection synchronously. It also creates a dedicated pump thread to do blocking I/O. You can use the ConnectionFactory.CreateAsync to create the connection and perform I/O operations asynchronously and take full advantage of the thread pool. However I am not if this is the root cause of the thread and handle count.

https://github.com/Azure/amqpnetlite/blob/master/test/LongHaulTest has an async test publisher which I use to test the library against SB queue. The AsyncTest is a good example showing how you can cache the amqp objects, implement auto-connect logic and perform async operations with tasks.

**Comment by BrianVallelunga** [comment]
Thanks for writing back. What's interesting about the slowness is that it doesn't appear at any repeatable time that I can tell. I've seen the issue under heavy loads and light loads, with both small and medium instances at Azure. From what I can tell, the slowness of the connection to ASB is the root cause of other issues, such as the high thread count and higher CPU use.

When testing, we're sending at most 5 - 8 messages per second for any one server. The number is usually around 1 - 2 per server since I prefer to spread the work across a few small servers. I've done load tests where a single small server will successfully process 50 - 100 requests per second without ever seeing an error or slow response.

I'll have a look at the LongHaulTest and see if restructuring my code has any affect. I was using the constructor to create the `Connection` object since the entire `AmpqClient` is only created a single time on the site's startup. I'll switch to the `CreateAsync` method and see if that improves things.

**Comment by BrianVallelunga** [comment]
I have a question about the code in https://github.com/Azure/amqpnetlite/blob/master/test/LongHaulTest/Role.cs

Isn't `EnsureConnectionAsync()` not thread-safe for a shared service such as my `AmqpClient`? It seems like I would want some locking around the actual creation since my client is being used by multiple threads. Perhaps I should be using `SemaphoreSlim` to ensure only one thread creates the shared `Connection` object at a time?

**Comment by xinchen10** [comment]
@BrianVallelunga you are right that the connection creation is not thread safe in the test since the test has only one producer per connection.

I cannot tell why exactly the slowness happened but I suspect it is still the server side issue. For example, if the service partition hosting your topic moved due to load balance or fault recovery, the link creation or message will be delayed.

You are also doing a sequential send. If one send is slowed down, your pipeline is slowed down. One way to increase throughput is to have parallel sends over the link. The LongHaulTest shows one way to send multiple messages and wait for all of them to complete. You could start the asyn send as soon as you have data available to send, or maintain a queue of messages and drain the queue based on a count or size threshold in your SendAsync implementation.

**Comment by BrianVallelunga** [comment]
I'll look at doing sends in parallel or queuing/batching in front of the ASB queue, which seems a bit unfortunate, but I understand why.

I've been trying to keep things simple with regards to the flow of data on this site. It's one and only job is to take form posts/json and convert them to messages that are sent to ASB. Right now the flow of data is simply: 1 HTTP POST -> Validation -> 2 ASB messages sent.

I've been running a newer version of the code (with the above thread-safe `Connection` creation) in production for about 20 hours now and I haven't seen any issues.

Do you have any idea if the official Azure Service Bus client for .NET Core will internally batch messages or use any other of these optimization techniques such as link caching? I ask because I know it will be based on AMQP and I'd like to switch to that long-term if it performs well and is stable.

**Comment by xinchen10** [comment]
If you call SendAsync as soon as you receive an HTTP POST, you are already doing parallel sends. I think they are all blocked on the lock for connection creation and that's why you also have high thread count. If you make the connection creation async, it should solve the thread count and memory issue. Once the connection and link is ready, the pending sends should be completed very quickly.

The SB dotnet client is under development. The only way to find if it performs better than this library is to try it out and compare.
