### ISSUE TITLE
ContainerHost.AddProcessor cannot handle same address from different sessions

### ISSUE THREAD

**Issue by nextra-Team** [Azure/amqpnetlite#205]
Called by AddLink from ListenerLink.OnAttach the first client can attach, but more client get an exception.How can this be solved

**Comment by xinchen10** [comment]
@nextra-Team can you be more specific about what the issue is?

After you register a processor at a given address, multiple clients can attach to that address even from different sessions.

By address do you actually mean link name? If you create multiple links with the same name and try to attach them to the same ContainerHost, only the first one will pass and the remaining ones will fail. This is required by the protocol spec.

**Comment by nextra-Team** [comment]
Could be that i try it on the wrong way as i don't know all the specs. I think there are many more like me. It would be great if you could write a small doc when to use which kind of processor (point to point, multiple client to single server, ???).

**Comment by xinchen10** [comment]
We have one doc for listener:
https://github.com/Azure/amqpnetlite/blob/master/docs/articles/listener.md
It gives very high level overview of the processor classes. Let me know if anything is not clear and I will try to update it with more details.

There is one example showing the usage of ILinkProcessor:
https://github.com/Azure/amqpnetlite/tree/master/Examples/Listener/Listener.ContainerHost

The tests for ContainerHost are also good references:
https://github.com/Azure/amqpnetlite/blob/master/test/Common/ContainerHostTests.cs

It also helps If you just post your code here and it's probably the easiest way to find the issue.
