### ISSUE TITLE
About receiving/processing malformed AMQP messages

### ISSUE THREAD

**Issue by ChugR** [Azure/amqpnetlite#211]
I've been working with project [Apache Qpid Dispatch](http://qpid.apache.org/components/dispatch-router/), an AMQP message intermediary. Along the way I stumbled across some cases where illegal AMQP frames are sent to clients and brokers and the clients and brokers accept them without complaint. For details please see [this issue](https://issues.apache.org/jira/browse/PROTON-1509). I filed this as a basis for discussion in Apache Qpid Proton as that project generally holds the AMQP brains for the rest of the Qpid projects. 

During tests I fed some of the illegal packets to a AMQP.Net Lite client and that client accepted the message with no complaint. Widely diverse AMQP processors accept these messages: AMQP.Net Lite, Qpid Proton C clients, Qpid C++ broker, Qpid Dispatch Router, and Wireshark.

Obviously for performance reasons AMQP client libraries do not want to examine every bit of every message. On the other hand there might be a down side to forwarding messages with invisible  or inaccessible content.

Is this really an issue and if so what should be done about it?

**Comment by xinchen10** [comment]
@ChugR in your test, does the amqpnetlite client (ReceiverLink) return a Message object to a receive call? It should not happen because the message decoder should throw exception when trying to read a section from the encoded string payload. I tried something similar and the client does throw. The exception will cause the link to be closed and application can read the error from Closed event handler or the Error property.

**Comment by ChugR** [comment]
A fresh build from current source shows:

> Exception Amqp.AmqpException: The format code '10' at frame buffer offset '243' is invalid.

This is a great error message and pinpoints the problem. 

The code that accepted the message was stale.
