### ISSUE TITLE
Creation of AMQP connection never returns in Xamarin.iOS

### ISSUE THREAD

**Issue by mintyfusion** [Azure/amqpnetlite#219]
This call never returns: `var connection = new Connection(new Address(connnectionString));`

The culprit seems to be how async Task functions are implemented and it looks like the Thread is getting blocked.

This is where the call gets stuck: `System.Net.Dns.GetHostAddressesAsync("yourhostname.servicebus.windows.net");`

**Comment by xinchen10** [comment]
@mintyfusion are you calling it from the UI thread? Try using ConnectionFactory to create the connection asynchronously.
```
var connection = await Connection.Factory.CreateAsync(new Address(connectionString));
```

**Comment by mintyfusion** [comment]
Yes, it's being called from the UI thread; once the app starts running. The end result is the same, but I didn't dig in that case where it's getting stuck. If you like I can send a sample app which shows this behavior.

**Comment by xinchen10** [comment]
I did some quick testing with mono WinForms app and the async creation is working. The sync creation is stuck as expected. I will try it on Xamarin later.

**Comment by PiotrSpikowski** [comment]
I have encouraged the same issue. I cannot however agree with an explanation given by @xinchen10 saying that a sync action may simply stuck.

In my opinion, if the library provides a synchronous version of the API then this API should work (especially when called from other synchronous methods). The controversial point can be when one wants to mix synchronous calls with asynchronous ones. I will focus here on the fully synchronous version. I will later try to post a separate issue about a mixed case (sync, async).

The problem is in fact wider than what @mintyfusion has described. It is not only related to Xamarin. It will not work in WinForms applications, WPF applications, ASP.NET applications and more. So if I have something like this in the ASP.NET app:

```csharp
public ActionResult SampleMVCAction()
{
   Open open = new Open
   {
      // Some open params here
   };
   var connection = new Connection(new Address("amqp://localhost:5672"), null, open, (_, __) => { });
   var session = new Session(connection);

   session.Close();
   connection.Close();
}
```

it will simply stuck. Please note that the entire action (MVC in this case) is synchronous. It is a simplification. In reality you may have a bunch of code which you do not want to change to be asynchronous.

The above code will stop at the creation of the Connection. This is because the library is trying to do something like this:
```csharp
this.ConnectAsync(address, factory).ConfigureAwait(false).GetAwaiter().GetResult();
```

The library takes the async code and is trying to make a synchronous call. So the synchronous version is “_pretending_” to be synchronous. The problems start when you have a `SynchronizationContext` allowing only one chunk of code to run at a time. This is the case for UI, ASP.NET and more. When the `await` completes (used internally on the `GetHostAddressesAsync` in our sample) continuation must be run using the captured context. It is not possible as the context is already busy waiting for the `async` method to complete. We have a deadlock.

The above will run with no issue in a console app where there is no `SynchronizationContext` and the continuation will most likely be schedule on the thread pool thread.

**Comment by xinchen10** [comment]
@PiotrSpikowski you are right about this one. Mixing sync and async method calls is another common reason for deadlock. But in this case it is the SynchronizationContext that causes deadlock. I will add ConfigureAwait(false) to all external tasks to "fix" this issue but in general app should use async methods in such cases if possible.

**Comment by xinchen10** [comment]
Please try 2.1.1 and reopen the issue if it is still not working.
