### ISSUE TITLE
Pass OnClosed callback to link constructors

### ISSUE THREAD

**Issue by mcmellawatt** [Azure/amqpnetlite#224]
We are registering an OnClosed event handler with our SenderLink and ReceiverLink, but it is after construction and potentially after attachment so it is possible that we miss the Closed event.  Would it be possible to add another parameter to the SenderLink and ReceiverLink constructors to allow passing an OnClosed callback, which would be registered before the links attempt to attach?  Here is some sample code of what we are doing:

```
                _amqpLink = new SenderLink(
                    session,
                    LinkName,
                    new Target() { Address = MessengerIDs.AdminMessengerID },
                    onAttached);

                _amqpLink.Closed += closedCallback;
```

As you can see, if the link attaches and closes before

`_amqpLink.Closed += closedCallback;`

is called, we will miss the Closed event.

This seems like a relatively easy fix considering we can already pass an OnAttached callback as a constructor argument.  The callback would need to be registered before the link attempts to attach so that there is no chance of missing the Closed event.

**Comment by mcmellawatt** [comment]
If you want to assign this issue to me, I can take a crack at it and submit a pull request.  Your call...I'm sure you know the code better than I do =).

**Comment by xinchen10** [comment]
This is indeed an issue. For the same reason the OnAttached and other similar handlers for Session/Connection open were taken from constructors. It was not done for the closed handler because it is common for all AmqpObject types and exceptions from send/receive calls serve the similar purpose. More importantly an AmqpObject instance may be created by a factory and then be managed by multiple components, each of which needs to listen for the Closed event to clean up component specific resources. So having the closed handler in the constructor makes it difficult to implement this scenario. To solve this issue I was thinking adding a new method to the base class AmqpObject, e.g. RegisterClosedHandler. It guarantees that the handler is invoked once even if it is registered after the object is closed. What do you think?

**Comment by mcmellawatt** [comment]
That sounds like a valid solution to me.  As you said, as long as there is a guarantee the handler is called even if the object is closed before we register, that should solve the issue.

**Comment by mcmellawatt** [comment]
Hi Xin - it looks like you've added a fix for this.  Any chance we can push this fix into a release?

**Comment by xinchen10** [comment]
2.0.0 released.
