### ISSUE TITLE
Supplying Error when rejecting message closes session (.NET Core 2.0)

### ISSUE THREAD

**Issue by emilpeder** [Azure/amqpnetlite#243]
When receiving a message through the callback supplied to the ReceiverLink.Start() method, and then rejecting the message by a call to ReceiverLink.Reject(Messsage, Error), then the ReceiverLink is closed, which seems to be due to the underlying Session being closed. The problem only occurs if one is actually setting the Error object to a non-null value when calling Reject().

I have attached a sample project demonstrating the issue.

[Program.zip](https://github.com/Azure/amqpnetlite/files/1554472/Program.zip)

**Comment by xinchen10** [comment]
@emilpeder which broker are you using? I think the problem is with the Error object that does not have condition set. The condition property is mandatory per the spec. Can you try setting the error condition to see if that fixes the problem? There are a few ways we could do to make it obvious when creating an Error object.

**Comment by emilpeder** [comment]
Hi Xin Chen

I am using ActiveMQ.

And you are right, when I set the Condition property, it works fine. Where
can I find the spec/documentation describing this, you are referring to?

Br.
Emil

2017-12-14 18:56 GMT+01:00 Xin Chen <notifications@github.com>:

**Comment by xinchen10** [comment]
@emilpeder you can find the protocol spec here,
http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-overview-v1.0.html

In section 2.8.14, the condition field is defined as mandatory.
