### ISSUE TITLE
Why is Coordinator not inheriting from Target?

### ISSUE THREAD

**Issue by springcomp** [Azure/amqpnetlite#252]
I'm trying to make sense of the AMQP specification and specifically its type system and the notion of archetypes. From what I gather, an archetype somehow restricts the values that a particular field can have. In my understanding, I see archetypes as "base-classes" in the OO sense.

For instance, the "declared" AMQP type provides the "delivery-state" and "outcome" archetypes, which means that the Declared type has a base class "Outcome" which itself has a base class "DeliveryState".

But this understanding falls apart when looking at the "source" or "target" AMQP types which provides themselves. In the particular case of the "coordinator" AMQP type which provides the "target" AMQP type, why is the C# Coordinator class not inheriting (or, at least having all the fields defined) from the C# Target class?

**Comment by xinchen10** [comment]
In the spec there is no inheritance in the xml type annotations. Coordinator is a described list with only one field. It does not have all the fields defined in type "target". It might be a bug or intentional but I am not sure. One way to interpret this is that archetypes are not necessarily the defined types with exact name match. For example, outcome, delivery-state and others do not even have a formal definition in the spec. So I guess archetype "target" is not necessarily the type named "target". In attach the source/target is defined as *, so as long as a type claims to provide target it can be set there.

**Comment by springcomp** [comment]
Thank you for your feedback. This is somewhat clearer. Thanks.
