### ISSUE TITLE
Should Session be reused per link

### ISSUE THREAD

**Issue by rwestonbutler** [Azure/amqpnetlite#253]
I've been searching this repo and the AMQP spec trying to find out if sessions should be reused, much like connections. Anyone have any guidance? Example in the following code snippet.. I create a persistent connection when the application starts, but wondering if the session should also be persistent, i.e., this.persistentConnection.GetSession() or something like that. In the below code, this.persistentConnection.CreateSession() is creating a new session using the connection every time it's called.

```
if (!this.persistentConnection.IsConnected)
                {
                    this.persistentConnection.TryConnect();
                }

                ISession session = this.persistentConnection.CreateSession();
                IReceiverLink receiver = session.CreateReceiver(this.persistentConnection.ContainerId, eventName);
                receiver.Start(
                    50,
                    (link, message) =>
                    {
                        byte[] body = message.GetBody<byte[]>();
                        var messageData = Encoding.UTF8.GetString(body);
                        this.ProcessEventAsync(eventName, messageData).GetAwaiter().GetResult();

                        receiver.Accept(message);
                        message.Dispose();
                    })
```

**Comment by xinchen10** [comment]
Session is important if you need (1) session level flow control (2) grouping links or (3) some higher level contract scoped to session (e.g. JMS transactional session). Otherwise you can create the session when you need to create a link. Session itself is very light weight.

Instead you need to think about if the link object should be kept around. If you send a message once in a while, it is ok to create a link, send the message and close the link. But if you have many messages to send or receive, it is much more efficient to reuse the link.
