### ISSUE TITLE
Use BufferManager to allocate frame buffer in sync Pump

### ISSUE THREAD

**Issue by szehetner** [Azure/amqpnetlite#264]
Is there a reason why `Reader.ReadFrameBuffer` (called by `Connection.Pump.PumpThread)` allocates a new ByteBuffer (and byte[]) instead of reusing one with BufferManager? AsyncPump does use the BufferManager, so I guess the sync Pump could also do this.

**Comment by xinchen10** [comment]
yes it should. The sync code path was written for netmf. For other platforms there is really no reason to use that. The problem is that creating a connection through constructor is the first choice for most people and they do not realize that underneath it is doing blocking I/O. I was thinking about deprecating the constructors and only use factory to create connections. The alternative is to fix the constructors (non-blocking I/O and buffer management) but there will be some work needed.

**Comment by szehetner** [comment]
Thanks for the clarification. I am porting a service from Apache NMS and went with the sync version first because it is more similar to NMS. I planned to switch to async anyway, but will just do that sooner. Also because I need a few TCP settings that can only be changed through the ConnectionFactory.
