### ISSUE TITLE
Use of SendAsync from multiple threads can result in deadlocks

### ISSUE THREAD

**Issue by nicodeslandes** [Azure/amqpnetlite#287]
If multiple threads use the `SenderLink.SendAsync` method to send messages to a common set of queues, a deadlock can occur.
Here's a sample code that exhibits the issue:
```csharp
// Open 2 connections and sender links to 2 queues
var connection1 = await Connection.Factory.CreateAsync(
    testTarget.Address, new Open() { ContainerId = "c1", MaxFrameSize = 4096 }, null);
var connection2 = await Connection.Factory.CreateAsync(
    testTarget.Address, new Open() { ContainerId = "c2", MaxFrameSize = 4096 }, null);
var senderLink1 = new SenderLink(new Session(connection1), "Sender 1", "q1");
var senderLink2 = new SenderLink(new Session(connection2), "Sender 2", "q2");

// Start multiple sender tasks that will use both sender links concurrently
var tasks = Enumerable.Range(0, NbProducerTasks).Select(_ =>
    Task.Run(async () =>
    {
        // Send 10 messages on both queues
        for (int i = 0; i < 10; i++)
        {
            var message = new Message() { BodySection = new Data() { Binary = data } };
            await senderLink1.SendAsync(message, TimeSpan.FromSeconds(10));
            await senderLink2.SendAsync(message, TimeSpan.FromSeconds(10));
        }
    }));
```

The problem is that after an async send operation execute, `SenderLink` will run task continuations inside of a lock. That is a problem is such a continuation attempt to call itself `SendAsync` on a different connection, as this will take another lock.

**Comment by billpoole-mi** [comment]
It would be great if we could get a patch released on nuget.org containing this fix ASAP.

**Comment by billpoole-mi** [comment]
Although the example code highlights the issue with two connections, would I be right in saying that the issue will also arise with multiple sender links on the same connection and session? We're experiencing a deadlock in SendAsync sending to two different queues using two SenderLinks (one for each queue) on different threads on the same connection and session. Notably also when the deadlock occurs, the SendAsync method isn't timing out after the given timeout has expired.

**Comment by xinchen10** [comment]
This issue should not be applicable to one session. It happened when different threads acquired multiple session's locks in different order. I updated your unit test to use one connection/session and didn't see the deadlock even without your changes. If you can reproduce the issue, please take a look at the threads to check what is the deadlock.

I will be releasing a new package soon.

**Comment by billpoole-mi** [comment]
I'm not the one that reported the original issue, but found this issue when looking to see whether my issue had already been reported.

I'm able to reproduce the issue reasonably regularly, however I haven't written an isolated test to do so. What would be the easiest way for me to determine where in the code the deadlock is occurring? So far I've confirmed that all threads are waiting for SenderLink.SendAsync to return a task. 

That is, it's not that the task returned from SendAsync never completes. Rather, I'm finding that when the deadlock occurs, SendAsync never returns a task at all. I can also confirm I'm not mixing sync and async methods and that the issue exists with both v2.1.2 and v2.1.3.

Note that the issue arises *only* when sending to two or more queues. The same code sending to a single queue never has a problem.

**Comment by billpoole-mi** [comment]
By the way, I've been looking at the SendTask class in TaskExtensions.cs and noticed that the timer isn't disposed after the timeout expires. That is, shouldn't the OnTimer method on line 312 have thisPtr.timer.Dispose() inserted as its second line?

**Comment by billpoole-mi** [comment]
It's looking like the reason why the task returned from SendAsync doesn't complete with a TimeoutException after the given timeout is that the SenderLink.OnTimeout method call in SenderLink.SendAsync on line 215 in TaskExtensions.cs doesn't ever return once the sender link is in its deadlocked state.

**Comment by billpoole-mi** [comment]
Okay, I found the problem and it was of my own making. The problem was that I was opening a sender link to a queue while another sender link to the same queue was in the process of being closed. This resulted in the call to create the new sender link never returning, but also method calls to other sender links never returning either. It seems that it causes a deadlock at the session level.

Although this is clearly a "user" error, I would have thought that this would result in the library throwing an exception rather than resulting in a deadlock. An exception would have highlighted my error immediately.

My only question outstanding then is whether a line should be added to the OnTimer method (line 312 of TaskExtensions.cs) to dispose the timer.

Thanks heaps for your assistance.

**Comment by billpoole-mi** [comment]
Turns out that a deadlock occurs when opening any link on a session while another link on the same session is closing. I think it is valid for a program to open a link while another is closing on the same session, so I've opened as separate issue for this here - https://github.com/Azure/amqpnetlite/issues/303#issue-358467125.

I've also added another issue asking whether the timer should be disposed in the OnTimer method in TaskExtensions.cs here - https://github.com/Azure/amqpnetlite/issues/304#issue-358468213.

**Comment by billpoole-mi** [comment]
Just in case anyone is interested, I've been able to reliably produce a thread deadlock on v2.1.3 by receiving from and sending to (on different threads) a single queue where the receiver link is created with a very low initial link credit (e.g. 10). This is on a single sender link and a single receiver link, both on a single session. 

However I tested the scenario on the master branch and it does not occur. So it seems that this fix has also fixed that.

I produced the deadlock with the following test scenario:
1. Open a receiver link to queue "q1" with a low initial link credit (e.g. 10).
2. Set up a message pump that receives messages and farms them off to a handler.
3. The handler waits a random delay up to 5ms, sends a new message to "q1", then accepts the received message.
4. Send 100 initial messages to "q1" with an average size of around 50kB.

The higher the initial link credit, the lower the probability of a deadlock occurring. I assume therefore that the deadlock is caused by ReceiverLink.SetCredit being called on the same session as Amqp.SendAsync with very specific timing.

Note however that this fix has not resolved the deadlock scenario I mentioned above (https://github.com/Azure/amqpnetlite/issues/303#issue-358467125).
