### ISSUE TITLE
port for .NET nanoFramework 

### ISSUE THREAD

**Issue by josesimoes** [Azure/amqpnetlite#294]
Hi,

Since .NETMF become defunct, I've been working along with other folks on nanoFramework, a revised and augment spinoff of .NETMF.
We now have networking capabilities and therefore having AMQP component is a must have. 
Can I submit a PR to add support for this platform?

**Comment by xinchen10** [comment]
That would be great. This project was started for netmf and then expanded to all popular platforms. Since netmf is going away I have slowly moved netmf projects to its own location and package. This is also needed to build the sources and the package on .net core in non-Windows environment. We will need to maintain this when adding nano platform support.

**Comment by xinchen10** [comment]
@josesimoes I can certainly release the nanoFramework package but I think it may be better for you to own the NuGet package and releases. I don't have the necessary tools and devices to test the nanoFramework libs. If you do all the work and wait for me to release it, it is just overhead and unnecessary delay. We will keep the code in one place but when it is ready the packages can go out on its own vehicle. What do you think?

**Comment by josesimoes** [comment]
I understand what you are saying and that makes sense. Just not sure what would be the best procedure/workflow to handle a new release or keep a decent CI... 
We can fork it to our org and keep in sync with the upstream. If the build breaks, you can notify us.
When there is a release you can ping us and we'll run testing on real hardware.

Does this makes sense to you/is doable?
