### ISSUE TITLE
Doing Request/Response initiated from IoT Core device

### ISSUE THREAD

**Issue by fabsenet** [Azure/amqpnetlite#31]
Hi,
I want to send a message from a Raspberry Pi (Windows 10 IoT Core) to a normal service running on a normal PC (Win 10/.Net 4.5.2). I already consumed this part from the amqp specification: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#section-transport

My question is: Is there a buildin way to send a message and receive the response correlated to it? Is this the Listener stuff? I can get the "Outcome" if I send a message, but it does not have a Message anywhere?

thx

**Comment by xinchen10** [comment]
Are you doing request/response between two peers, or through a broker?

If it is P2P communication, please check out the examples PeerToPeer.Client/Server. The client sends request messages to an address and receives response messages from it. The server (request processor) listeners on an address and responds to request messages.

If it is brokered communication, please check out the examples Interop.Client/Server. The communication is done through a queue and a temporary response queue.

On client side right now you would have to use two links to send/receive messages. For P2P server the request processor API should make it easier to handle requests.

**Comment by fabsenet** [comment]
Hi thanks for quick reply!

In your words, I am doing Peer2Peer without broker. Late last night, I was copying stuff from the peer2peer samples and got it basically working :+1: 

Stuff I do net get conceptually is "Attach" on the client side. If I supply my request message already with a reply-to property, what else is the attach for?

On the server side, I do not only need the RequestProcessor but also a LinkProcessor. But what does it really do?

I do not want to take your time too much. Is there a documentation piece somewhere for this?

**Comment by xinchen10** [comment]
In P2P mode, the server needs to know where to send back response messages. The pattern for this scenario is to have the client announce a unique address while attaching the receiver link (the value is set in attach.target.address field). Now the server can find that link by using message.reply-to and send the response over that link. This is required because there might be multiple clients connecting to the same server so the server needs a way to correlate send/receive links from one client.

You can find more information in the proposed AMQP management protocol (https://www.oasis-open.org/committees/download.php/54441/AMQP%20Management%20v1.0%20WD09). You can directly go to section 4 and 5.

On the server side, you do not need LinkProcessor. As long as you have a RequestProcessor registered, the client should be able to connect. LinkProcessor can be used when you (1) want to access the link creation event to perform server side initialization/extra validation; (2) need to handle attaches to address where no message/request processors are registered. When an attach command comes, the server first looks at registered message/request processor addresses, if no match and a LinkProcessor is set, it invokes the LinkProcessor to handle the attach command.

**Comment by fabsenet** [comment]
Got it working without the LinkProcessor. My Client had two receiver links with the same name which is not correct. somehow the linkprocessor helped me here before....whatever :+1: 

I am getting there.

What I want to do is send another message to the client after the inital response was send, but the ResponseContext does only have Link property of type ListenerLink. I suppose this is the Link which received the initial request. What I need is a way to get hold of the session to that particular client or a SenderLink to that client, so I can save this instance and use it later.

My Scenario is distributed lighting with a central configuration:
Client=>Server: "Hi, i am device 'raspberry1', what is my config?" (config request)
Server=>Client: "You have a light on pin 18" (config response)
Server=>Client: "set light on pin 18 to high" (commands)
Server=>Client: "set light on pin 18 to low"
Server=>Client: "set light on pin 18 to high"

**Comment by fabsenet** [comment]
Only if you like:

You can have a look at my processor here, the commented stuff does not work as i want it to:
https://github.com/fabsenet/HomeControl/blob/master/CentralService/DeviceConfigProcessor.cs#L56

**Comment by xinchen10** [comment]
If you call `requestContext.Link.SendMessage(msg, msg.Encode());` it should work. It would make more sense to do this before you call requestContext.Complete() which sends the last message (there is no enforcement in the library though).

**Comment by fabsenet** [comment]
I cant help it, it just does not work the way I want.

My latest state of the server side is here:
https://github.com/fabsenet/HomeControl/blob/7e9321866c327173f52c784fc0a9619edf2d46e5/CentralService/DeviceConfigProcessor.cs#L58-L82

If I don't do the complete() call (commented out; line 57), the client even does not receive the first response and the server throws an AmqpException later with message "Operation is not valid due to the current state of the object.". But which object? and which state? it is rather disappointing.

Can you help?
Or can you extend the examples to show off a publish/subscribe?

I want to be honest with you. I am feeling like I have to swap out amqpnetlite. I chose it, because I want to do real messaging and no fake stuff over http and I want to do .net and i want to do IoT. in the "management summary" it all looked good, but now, I am not that sure anymore.

**Comment by xinchen10** [comment]
Sorry, I gave you a wrong answer. That ListerLink cannot be used for sending responses. It is actually simpler to get what you want by just calling RequestContext.Complete(Message) whenever you need to send a response. I updated the samples which now send 11 response messages for 1 request message.

**Comment by fabsenet** [comment]
okay this works now, but I am not sure how to go further.

My client knows the address of the server and not the other way around and because of a router/NAT in between, the server could not open a connection on its own to the client but still, I want to get notified, if the connection is not alive anymore. Do I need to implement an application level ping command for this? Because I do not find a proper api on the requestContext.

And is it by design or by accident that it is possible to call Complete() multiple times? because of its name, it feels wrong to me.

Or do you think I want to use AMQP for the wrong thing? Because the q means queueing and what I really want is two-way sync messaging. Should I better switch to wcf (or something like it which is available for UWP apps)?

On another path of exploration, I tried to replace my RequestProcessor with a MessageProcessor and I tried to use the underlying session to build another sender:

```csharp
public class MyMessageProcessor : IMessageProcessor
{
    public void Process(MessageContext messageContext)
    {
        var session = messageContext.Link.Session;
        messageContext.Complete();
        session.Connection.Closed += (o, error) => Console.WriteLine("connection closed!");
        var sender = new SenderLink(session, "mySecondSender", "command");
        sender.SendAsync(new Message("hallo1")).Wait();
        sender.SendAsync(new Message("hallo2")).Wait();
        sender.SendAsync(new Message("hallo3")).Wait();
    }

    public int Credit => 300;
}
```

..and I enabled tracing to see whats going on. In the first SendAsync, it sends an Attach message but then only produces a timeout later. My client does not do anything and I - again - was unable to find the proper api to handle the attach.

**Comment by xinchen10** [comment]
Calling Complete multiple times is a workaround. I have fixed it by having ResponseLink on RequestContext which can be used to send response messages if needed.

AMQP does not restrict who initiates a link creation, but most implementations including amqpnetlite do not support accepting links on client APIs. That's why there is a clear distinction between client and listener APIs. In case of failures, the client has to re-connect.

I modified the PeerToPeer.Client/Server sample to do just request/response. The client and the server both handle communication exceptions to complete the 1000 iterations. When either of them fails, the communication resumes from the last known offset. The failures can be simulated by simply killing either the client or the server while they are running.

I am not sure if this is what you need.

**Comment by xinchen10** [comment]
I don't know what else is needed for this issue. Please reopen it if you have any other specific questions.
