### ISSUE TITLE
Credits don't decrease instantly when calling SetCredit

### ISSUE THREAD

**Issue by Necriis** [Azure/amqpnetlite#339]
I have a particular use case where I need to add and remove credits to avoid starvation of my receiver link. (As ServiceBus, when releasing a message, doesn't apply a delay before re-sending the message, I wanted to add 1 credit, start a timer, and when the timer ellapsed, remove this extra credit and complete the message properly)
In the version 2.1.6, there was a bug on the 'restored' field that was reset when calling SetCredit (in auto mode, always), so I hacked it like this:
```csharp
int restored = (int)typeof(ReceiverLink).GetField("restored", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(this.Receiver);
this.Receiver.SetCredit(newCredit);
typeof(ReceiverLink).GetField("restored", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(this.Receiver, restored);
```
And it works pretty well.

But this bug has been fixed here #326 and a regression was introduced that causes the credit number to grow even if we call SetCredit with a lower value, until there is no more message to process or until the app run out of memory/socket/processor time (because for each message, there are processing, database connections/requests and messages sent to topics).

I have not yet taken the time to investigate this bug, I just wanted to report it and I will add more details when I have a more time to devote to it.

**Comment by billpoole-mi** [comment]
The SetCredit method doesn't instantly decrease the credit when a lower credit is passed in auto-restore mode because the receiver link must still be able to receive the messages sent by the peer in response to the original credit (before it was reduced).

Therefore, the receiver link waits until it reaches the auto-restore threshold to auto-restore, but then only restores to the allowed credits specified by the earlier SetCredit call.

Note that this was also the behavior in version 2.1.6. The fix for #326 changed the behavior to include the restored credit at the time SetCredit is called in the credit value sent in the Flow frame, before setting the restored count to zero. The alternative would have been to *not* reset the restored count and also *not* include the restored credit in the credit value sent in the Flow frame. As it was before the fix, it *was* resetting the restored count to zero and *not* including the restored credit in the credit value sent in the Flow frame.

Starvation shouldn't occur with a receiver link in auto mode in version 2.1.7. Does this starvation issue occur if you remove the 'hack' code and use the receiver link as is?

If you call SetCredit with a *higher* credit, then it is immediately actioned by the receiver link. So, when you add 1 credit and start the timer, a Flow frame should be immediately sent by the receiver link to inform the peer of the new credit.

After the timer expires and you call SetCredit with one less credit, that reduced credit isn't immediately communicated to the peer; but communicated when the next auto-restore occurs. So credit shouldn't be growing unbounded.

However, given your use case, have you considered instead of 'releasing' the message (which will be immediately redelivered), using the 'modified' delivery state to specify a delivery delay using the 'x-opt-delivery-delay' message annotation? I don't know whether 'x-opt-delivery-delay' is supported by Azure Service Bus, but it's supported by ActiveMQ/Artemis.

**Comment by xinchen10** [comment]
@Necriis by decreasing the credit are you trying to prevent the library from sending a flow with restored credit when you complete/release the message?

I think for your case you could simply use the manual credit mode. When you call `SetCredit(1, CreditMode.Manual)` and receive a message, the link credit is now 0 on both ends and you will not get more even after you accept or reject or release the message. You make the call again when you need another message.

**Comment by Necriis** [comment]
@billpoole-mi : unfortunately, 'x-opt-delivery-delay' is not supported by ServiceBus 😞😞
@xinchen10 : indeed, you're right, for my case the best and simplest thing to do seems to go manual. But I miss something like a ForgetMessage method that could silently cleanup things like the session incomingMessages list (to prevent memory leak) and do as if I never received the message, waiting for the lock to timeout, and the message to be redelivered...
