### ISSUE TITLE
Problem with message body deserialization.

### ISSUE THREAD

**Issue by kanovsky** [Azure/amqpnetlite#344]
I am having trouble with reading body of the message using:

`message.GetBody<string>();`

I am getting this error:
error(condition:amqp:decode-error,description:The format code '176' at frame buffer offset '136' is invalid.)

Can I troubleshoot somehow what is wrong?
Otherwise I can read header and properties of messages, only problem with getting body.

I assume there is a problem with 3rd party ActiveMQ server, whose messages I am trying to pull, but it is now problem to tell what exactly is wrong.

Thank you.

**Comment by xinchen10** [comment]
176 (0xb0) is the format code for AMQP type bin32. I think the message body has a binary value instead of a string. In other words the body contains an AMQP value section whose value is a binary. Since you specify the type parameter to be `string`, the library is trying to decode a string from the buffer (which actually is a serialized byte[]).
Try calling `message.GetBody<byte[]>()` to see if it works. GetBody<T> requires you to know the exact type of value in the message body.

**Comment by kanovsky** [comment]
Thank you, `message.GetBody<byte[]>()` works.

So it means now I need some specification of the format of this message body, to be able to deserialize it from the third party's ActiveMQ server side? Or can I do something else with this byte array? Originally I was expecting that body should be some JSON.

**Comment by xinchen10** [comment]
You will have to know how the value is encoded in the byte array in order to read the value back. That's an agreement between message publisher and consumer. If I have to guess, the byte array might be just UTF8 encoded JSON string.

**Comment by kanovsky** [comment]
Right, this works: `Encoding.UTF8.GetString(bytes);`
Thank you and sorry for a bit silly question. :)
