### ISSUE TITLE
How to send `Exception` object through sender

### ISSUE THREAD

**Issue by GaikwadPratik** [Azure/amqpnetlite#353]
@xinchen10 ,

I have defined a custom Exception as below:

```
[AmqpContract]
    public class AmqpResponseException : Exception
    {
        [AmqpMember (Name = "code")]
        public string Code { get; set; }
        public AmqpResponseException(string message = "") : base(message)
        {
        }
    }
```

I am able to send it using `sender.send` but I am not able to get it back in the receiver.

How do I send and receive it using sender and receiver correctly?

**Comment by xinchen10** [comment]
Did you get exception from deserialization on the receiver, or you didn't get the message back from the exception object?

The serializer does not understand the Exception class, so the message property will not be sent. On the receiver side, since your class does not have a default constructor, the object is allocated but not initialized. The serializer will initialize the Code property but not the message.

You can try the following code but I am not sure if it works or not as I didn't run it.

```
        [AmqpContract]
        public class AmqpResponseException : Exception
        {
            [AmqpMember(Name = "code")]
            public string Code { get; set; }

            [AmqpMember(Name = "message")]
            public string message;

            public override string Message => this.message;

            public AmqpResponseException() : base()
            {
            }

            public AmqpResponseException(string message) : base()
            {
                this.message = message;
            }
        }
```

**Comment by GaikwadPratik** [comment]
I get something like:

```
{"Descriptor":{AmqpNetLiteRpcCore.AmqpRpcResponseException},"Value":["AmqpRpcUnknownParameter"]}
```
where value object holds `code` and `Descriptor` holds exception class name and there is no message.

With your suggestion now `Value` object has two properties with code and message. Am I correct in assuming, I will have to send a custom class not derived from `Exception` but populating necessary values from Exception?

**Comment by xinchen10** [comment]
You can derive from Exception but you will need to keep the message property in your class instead of passing it into the base Exception class. On the receiver side the serializer should give you back the right exception object.
