### ISSUE TITLE
Detach throws exception on ReceiverLink

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#355]
I am wondering why it is expected for Detach to throw exception when called on ReceiverLink? 

To add more context to my question, the problem only appears when I use built in ContainerHost. When I connect to ActiveMQ Artemis I can Detach without any errors. 

From what I see in the code this seems to be the culprit:

https://github.com/Azure/amqpnetlite/blob/d677f79855b04e58fc75bc3105a1fdb6021f53cf/src/Link.cs#L183-L187

``SendDetach`` totally ignores ``detach`` parameter and sends new ``Detach`` command with flag ``Closed`` set to ``true``. 

I suggest the following change to fix this issue. 

```
else if (this.state == LinkState.Attached)
{
    this.session.SendCommand(detach);
    this.state = LinkState.End;
}
```

**Comment by xinchen10** [comment]
Detach throws when the remote peer closes the link endpoint. Detach (closed=false) means the link endpoint state should be preserved so that the link can be resumed later. ContainerHost does not support link resume so it should not lie.

**Comment by Havret** [comment]
Thanks for reply. That makes perfect sense. I am using ContainerHost for my integration tests, but maybe there is a better way to test this particular scenario. I really don't want to write my own TcpListener.

**Comment by HavretGC** [comment]
Hi @xinchen10, thanks for feedback. What you are saying makes perfect sense. 

I am using ContainerHost to make assertions during my integration tests and it's been working quite well so far, but I hit the wall when trying to test detach scenario. Do you know by chance if there is any way to test this use case using amqpnetlite toolbox? Currently I am working on  activemq-nms-amqp failover implementation https://github.com/apache/activemq-nms-amqp/pull/4 which turned out to be one big rework. We are using amqpnetlite under the hood and would really appreciate any help.

**Comment by xinchen10** [comment]
We can update ILinkProcessor to also handle detach command, and determine if a link should be detached or closed. That should be possible.

**Comment by HavretGC** [comment]
I tried to implement it, in order to submit PR, but I stuck. I don't know if I should override the default behavior of detach (if so, how?) as it is done for attach or just hook into the pipeline?

**Comment by xinchen10** [comment]
I implemented the detach support in ILinkProcessor. Since we are adding a new method to the public interface, it is a breaking change and would need a major version increase. I will need to check any other potential breaking changes so I am delaying the merge to master. The changes are in the `listener-link-detach` branch. Is it possible for you to build the source and use the host in your test for now?

**Comment by HavretGC** [comment]
Thank you very much! I'm looking forward to the official release. Unfortunately I cannot build it myself, because I would need to push this build to our local nugget feed, to make it work with CI/CD. For now I circumvented the problem by adapting your `TestListener`.

**Comment by HavretGC** [comment]
I think this issue can be closed now.
