### ISSUE TITLE
support for virtualhosts?

### ISSUE THREAD

**Issue by danlangford** [Azure/amqpnetlite#36]
the QPID java broker has a concept of a "virtual host" and im wondering how to go about connecting to this kind of broker with the AMQPNetLite lib. 

I asked the same thing of the guys over at noodlefrenzy/node-amqp10#171 and they found that the Qpid Java Broker is expecting the virtualhost to be identified with the `hostname` field in some init frames. Is there a way in this lib i can specify what hostname value to send during initialization where the value may be different than the actual server hostname?

some amqp1.0 clients are supporting the url patten `amqps://user:pass@example.com:5671/default` where **default** is the name of the virtual host and as such is the value of the `hostname` field in the init frames

**Comment by xinchen10** [comment]
If your queue is in the default virtual host, you do not have to set a different hostname. Otherwise, you can set which virtual host to connect to by creating an Open command in the Connection ctor.
```
Address address = new Address("amqp://guest:guest@10.10.10.1:5672");
Connection connection = new Connection(address, null, new Open() { ContainerId = "test-container", HostName = "test" }, null);
Session session = new Session(connection);
SenderLink sender = new SenderLink(session, "sender", "q1");
Message message = new Message("Hello");
sender.Send(message);
connection.Close();
```
The Open.HostName field should match the virtual host name in the Java broker and a queue named "q2" should be created under virtual host "test". This worked against the 0.32 Java broker.
The library does not support defining the virtual host in the address string.

**Comment by danlangford** [comment]
wow this worked great. thank you very much.
