### ISSUE TITLE
Use object pool for commands?

### ISSUE THREAD

**Issue by szehetner** [Azure/amqpnetlite#375]
A lot of outgoing and incoming command objects are frequently created and have a very short and deterministic lifetime. That would make them ideal candidates for pooling. This could be used for all commands that are created internally and immediately sent or received and immediately handled without being ever visible to consuming code (e.g. not passed to a callback). Candidates are e.g. Flow and Transfer. This wouldn't catch all commands but it would be totally transparent to the consuming code. 

For outgoing commands Connection.SendCommand could return them back to the pool after they are encoded. For incoming commands Connection.OnFrame could return them after the OnXXX() method has finished. The fields bitmask introduced with #370 now also makes it easy to reset all fields.

Questions:
* Any objections to using an object pool in general?
* Should the classes implement an interface (IPoolable) or should DescribedList have a virtual method IsPoolable?
* Should the object pool be global or should it be scoped to e.g. a Connection? Scoping it to a connection could make it more useful in the future (visible and configurable by client code), but a global internal pool would be easier to use in e.g. Encoder where incoming commands are created. Lock contention shouldn't be an issue even for the global pool if we have use a ThreadStatic field per type as the first layer, which would probably catch 99% of all usages.

**Comment by xinchen10** [comment]
I don't have objections to pooling objects in general. We have buffer pooling support already in the library. The other one is string pooling in a pending PR. These two have been proven useful mostly because they enable efficient memory management by the app, However I don't have good experience with object pooling in a particular component. In many cases the app is accountable for most allocations when processing messages. It is also not easy to identify which object(s) to pool as it could vary based on usage pattern. If an object contains other reference types, they may need to be pooled as well. I am not pushing back to the idea. We can certainly do it when this is needed for real scenarios. I am open to ideas/opinions from others as well.
