### ISSUE TITLE
Strange AMQP error when closing receiver

### ISSUE THREAD

**Issue by zawodskoj** [Azure/amqpnetlite#384]
`ReceiverLink.CloseAsync` produces error in some cases

```
AMQ119005: error creating consumer, AMQ229200: Maximum Consumer Limit Reached on Queue:(address=*,queue=*)
  at Amqp.AmqpObject+<CloseInternalAsync>d__2.MoveNext () [0x001b9] in <20ebd10ee6194f65b6256a916ca14efa>:0
```

This is very unexpected and strange error (consumer creation error on close?).
Problem may intersect my another problem (same receiver just stops receiving messages without any errors, long before close)

I use AmqpNetLite 2.2.0 + Xamarin.Android

**Comment by Havret** [comment]
Are setting ChannelMax field during connection creation by any chance? 

https://github.com/Azure/amqpnetlite/blob/9b40a877fc1410ce3f1c3e2e2303c71f2845a359/src/Framing/Open.cs#L76

**Comment by xinchen10** [comment]
How do you receive messages, calling the Receive method or starting the receiver with the MessageCallback? When the receiver link is closed, calling any method, including close, will throw exception with the error. When using the message callback, it is better to also register a Closed event handler so that you will get notified when the link is closed.
