### ISSUE TITLE
ContainerHost should accept strongly typed Address

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#397]
Currently one can create ContainerHost only via string address (or list of addresses) that has the following form:

```
amqp[s] :// [user:[password]@] domain[:port] [/[path]
```

It's problematic as there is no symmetry between this and how one can create Connection. Would it be ok, if we introduce a new constructor overload that would accept strongly typed Address parameter and list of Addresses to bring it in line with connection factory methods? I could submit PR. 

@xinchen10 What do you think?

**Comment by xinchen10** [comment]
The `Address` class was introduced because `Uri` was/is not available on all supported platforms. The listener is supported only on full .net and .net core, so Uri was chosen instead. That caused the inconsistency unfortunately. I am fine with using `Address` in `ContainerHost` but just wondering what we should do with Uris. They look a bit redundant after we have `Address` types.

**Comment by Havret** [comment]
Yes, that makes sense, but can we just replace `Uris` with `Address` types? Wouldn't it be a breaking change?

**Comment by xinchen10** [comment]
We cannot remove `Uri`, at least for now. We will need to add `Address` and mark the `Uri` overloads as obsolete (and remove them in the next major release).

**Comment by Havret** [comment]
Ok. I will submit PR over the weekend, if you don't mind. :)
