### ISSUE TITLE
Connection or SenderLink as singleton

### ISSUE THREAD

**Issue by osekodk** [Azure/amqpnetlite#414]
I have an application with a service that can be used to send single message to a queue ad-hoc. What is the best practice regarding the lifetime of the connections / sessions / senderlinks, for such a scenario? Should a new connection be created for every message to send, or can a singleton connection be created on startup and used for the whole app lifecycle? Does the same apply to senderLinks? If it's not a bad practice I would prefer to create a senderLink per queue on startup, and use that as a singleton.

**Comment by xinchen10** [comment]
This is similar to HTTP Keep-Alive. You know the best when and how often you need a connection/session/link object to send a message. It also depends on how the broker manages resources. For example if you publish to a local broker infrequently you may not observe any difference between either approach. But if you use a cloud service then other factors (e.g. connection quota, per-operation charge, etc) may apply.
If you decide to implement the singleton model you will need to have reconnect logic because the connection or link can break at any time for various reasons.
