### ISSUE TITLE
Is async void safe?

### ISSUE THREAD

**Issue by Havret** [Azure/amqpnetlite#415]
I'm just wondering, is it safe to have the following method async void? 

https://github.com/Azure/amqpnetlite/blob/a16ee2ded504ef70185c83cf4914a9f82bf71da8/src/Net/TransportWriter.cs#L114

**Comment by xinchen10** [comment]
It is dangerous because any unhandled exception will cause the process to crash. That's why exceptions need to be handled and passed to the onException delegate. Any other exception (e.g. OutOfMemory from List.Add or callback exception from onException delegate) is considered fatal and we want the process to crash. It is safer than "async Task" because the caller is not observing the result/exception of the task which can cause the writer to stop permanently in case of unhandled exception.
