### ISSUE TITLE
Message.Properties enumerable like a dictionary

### ISSUE THREAD

**Issue by ppatierno** [Azure/amqpnetlite#42]
My AzureSBLite library that wraps the AMQP .Net Lite for Service Bus access (queues, topics/subscriptions and event hubs) has some methods to convert a BrokeredMessage and EventData instance from/to the Message class.

As you know, the correlation between properties (both application and system properties) is the following : 

BrokeredMessage/EventData.Properties <--> Message.ApplicationProperties
BrokeredMessage/EventData.SystemProperties <--> Message.Properties

The Message.ApplicationProperties is enumerable thanks to the exposed Map field but it's not possible for the Message.Properties field that is a DescribedList.
Could be possible to expose Message.Properties like a dictionary to enumerate it ?

Thanks,
Paolo

**Comment by xinchen10** [comment]
Many fields of Message.Properties can be mapped to BrokeredMessage properties directly (e.g. MessageId, SessionId, To, etc.). Enumerating the Properties list like a dictionary actually does not help much.

It could help EventData conversion, but I prefer it is done in the converter instead of the library. Message.Properties is defined as a list where the fields are identified by their position, not the name. The fields are already defined, so in the converter you could check the value of each field and add it to SystemProperties directly.

Thanks,
Xin

**Comment by ppatierno** [comment]
Yes on BrokeredMessage you are right.

On EventData it could help the converter to execute a simple "for" inside the dictionary for copying values to the SystemProperties collection of EventData instead of copying each of them with point-to-point assignment.

Paolo.

**Comment by xinchen10** [comment]
This is implementation specific and it would be better to have it in the converter code.
