### ISSUE TITLE
CoreCLR implementation

### ISSUE THREAD

**Issue by stephanjohnson** [Azure/amqpnetlite#43]
When can we expect to have this library implemented for CoreCLR?

**Comment by fsoikin** [comment]
I've managed to get it running on CoreCLR rc1-update1 (and on rc2 as well, barring issue https://github.com/aspnet/dnx/issues/3271)

I had to do three changes for this:

1. In `project.json` change the target from `dotnet` to `dnxcore50`, otherwise dnx refuses to load the library. I'm not quite sure whether `dotnet` is now deprecated altogether or if something else was missing. Haven't gotten around to figuring that out yet.
2. In `project.json` add the [SRAmqp.resx file](https://github.com/Azure/amqpnetlite/blob/master/src/SRAmqp.resx) as `namedResource`. It seems this file is only required for error reporting though. When everything is ok, its absence is not noticeable, but whenever anything goes wrong, you get a "resource not found" error.
3. Stop using the `Socket.BeginX`/`EndX` methods and rewrite the corresponding tasks in terms of `Socket.XAsync`, because the former [have been removed](https://github.com/dotnet/corefx/commit/2d6de874008b0ba74c877c5895847421f3adf1af) from the `Socket` contract in coreclr as of RC1.

My changes are here: https://github.com/fsoikin/amqpnetlite/commit/ff9ea7c5cbfe0853661c9b165e4e361d5f66f66f
Would you be interested in a pull request?

**Comment by xinchen10** [comment]
@fsoikin it would be great if you can send a PR. Just a question about item 1: is it a must to replace dotnet with dnxcore50? I read a few online posts about the new way to target frameworks and it is recommended to use dotnet if the library works on any platform as long as the dependencies are met.

**Comment by fsoikin** [comment]
I have read those posts, too, and tried `dotnet` first, and unfortunately, it doesn't work.

I hesitate to file an issue with the CoreCLR team yet, because they seems to be in the process of tossing these things around a bit. I will check back on this once they hit RTM.

**Comment by fsoikin** [comment]
Created a PR.
My contributor agreement is already signed.
