### ISSUE TITLE
Question: Client certificate in SaslProfile.OnCommand?

### ISSUE THREAD

**Issue by gorazspajzer** [Azure/amqpnetlite#476]
Hi!

When user connects to my broker I validate his certificate and if everything is ok with I return true.
I have 
`sealed class APISaslProfile : SaslProfile, IAuthenticated`
and in 
method 
`protected override DescribedList OnCommand(DescribedList command) `
I'm checking user (username and password) but not I would like also check his (supplied certificate) certificate because every user has certificate and I need to check username and password and check if supplied certificate is his.

Regards,
Gorazd

**Comment by gorazspajzer** [comment]
Thank you for fast response, but I have another problem. Method UpgradeTransport is newer called! Any clues why this is happening?

`        protected override ITransport UpgradeTransport(ITransport transport)
        {
            return transport;
        }
`

**Comment by xinchen10** [comment]
It is a bug. Because of that, the listener doesn't call UpgradeTransport of a custom SaslProfile implementation. After looking at it more closely, there are a few things worth mentioning.
1. SaslProfile implementation set on a listener is used for all transports accepted by that listener, so it is not a good practice to store per-transport state in that object.
2. UpgradeTransport is called after the SASL negotiation is done. 
3. There is no good way to return an error to the client due to certificate issue. The only option now is to close the transport.

In general cert-based transport level security is considered external to a SASL established identity. When client cert is used for authentication, it is often to use SASL EXTERNAL. But I understand that you may have a valid reason to require client cert and SASL PLAIN. We will make a few changes.
1. fix the bug so UpgradeTransport is called, where you can examine the client cert and close the transport if needed. Note that errors cannot be returned in this case.
2. add a new event (Id=SslStreamAccept) in IHandler for which you can register a factory with the listener. This allows you to check the SslStream right after it is accepted and reject it if needed. Again no errors can be returned to the client.
3. IHandler instance is created per transport, so you have the option to save the SslStream to your handler implementation, and delay the cert check until connection open. That allows an error to be returned to the client but you are allowing a transport to live longer before rejecting it.
