### ISSUE TITLE
Why are classes like DescribedList marked abstract and designed to prevent inheritance by classes outside of the library?

### ISSUE THREAD

**Issue by jziolkow** [Azure/amqpnetlite#482]
I have a need to send a composite type when constructing a source link to QPID-J broker instance. I have been unable to construct the type using the available public types in the client library that avoids a serialization error on the client side or an AMQP decoding error being thrown from the broker.

It appears that the DescribedList class implements exactly what I need (i.e. the specification of a descriptor with an empty field list). But, for some reason, the class cannot be directly instantiated. Inheriting it doesn't work because there are internal abstract members which means I cannot successfully implement the type in my derived class.

Am I missing something?

**Comment by xinchen10** [comment]
Due to the complexity of implementing `DescribedList` and `DescribedMap`, they are not expected to be used by application code.  They are designed for performance rather than ease of use. They are public classes because the protocol performative types (Open, Begin, etc.) need to be public.

You can use `DescribedValue` type for your need. It is less performant but in most cases it should not matter.

**Comment by xinchen10** [comment]
The value of "lifetime-policy" is a composite list. Try using a Symbol type for the descriptor when you create the `DescribedValue` instead of a string.

**Comment by jziolkow** [comment]
Thank you! Wrapping the descriptor in a Symbol type worked.
