### ISSUE TITLE
Receiving end() while processing messages prefetched

### ISSUE THREAD

**Issue by thorhalvor** [Azure/amqpnetlite#556]
Hi,
not sure if it is "by-design" or not. But it cause an unwanted issue for me.

I have an amqpnetclient  receiving messages from a RabbitMQ server, and set CreditLimit to for example 100.
RabbitMq has set timeout and will disconnect the session after  for example 5 minutes. That means, - if i have not processed the 100 messages fetched within 5 minutes the client will receive an end()-command from RabbitMQ with error=precondition_failed.

I assume this is bydesign, but my problem is that the end()-command does not get processed before all 100messages are processed. (all the transfer-commands must be processed). I would like the session to be closed immediatley when the end()-command "knocks on the door". that it is prioritized before all the 'transfer-commands' thas is queued up.
since the server has told me to end(), - all my messages are "released" on rabbitmq. (put back on queue, ready to be fetched again), so all mye dispositions-commands sent after the timeout will have no effect. - and i get "unwanted amount" of duplicates.

my application is set up for "atleast-once" and have duplicate-handling, but the way it works now will give me more duplicates than i think is necessary. if the client had just closed the link/session when the (end) was received. 

i know i did repeat myself, but i hope mye issue is easy to understand without having to create a code-example

examples of commands on the wire:

> SND open 
> RCV open 
> SND begin 
> RCV begin 
> SND attach 
> SND flow 
> RCV attach 
> SEND flow 
> RCV transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer transfer 
> SND disposition 
> SND disposition 
> SND disposition 
> SND disposition 
> RCV end 
> SND disposition 
> SND disposition 
> SND disposition 
> SND disposition

**Comment by xinchen10** [comment]
Do you call `ReceiverLink.Start(100, callback)` and process each message synchronously in `callback`? The protocol state machine has to process incoming frames in the same order they are received. So by-design all transfers have to be processed before the `end` command.

For your use case, you would need to call `ReceiverLink.Receive` in a loop. The library will queue the transfers if you do not process them fast enough. It also processes `end` as soon as it is received which closes the receiver link. When you call receive again, you would get an exception instead of queued messages.

**Comment by thorhalvor** [comment]
Ahh, thank you! i thought i had testet that approach first with various (corner)cases. but my last testcases was using Start with callback. When changing back to Receive in a loop as you say i get app the transfers on the wire immediately after "setCredit" and when I do get the the close-callback when end() is received. just what i wanted. without going through all the messages. and calling dispostion on them all. Cheers!

**Comment by kennethmyhra** [comment]
I'm jumping into this thread since I work on the same project as @thorhalvor 

@xinchen10 From the tests that @thorhalvor has been doing it seems to us `ReceiverLink.ReceiveAsync` has the same behavior as when using `ReceiverLink.Start(100, callback)` i.e. `end` is processed only when all messages before it in the queue has been processed.

Is this behavior to be expected?
