### ISSUE TITLE
Help: Setting max threads

### ISSUE THREAD

**Issue by Marvin-Brouwer** [Azure/amqpnetlite#572]
Hi,

I tried using your library to interface with an Azure ServiceBus, because we needed a sync alternative to microsoft's SDK.
However, the third party running our code is seeing a lot of threads.
I can see there's some level of configuration that can be done using a ConnectionFactory, however that only has a CreateAsync method.

Is there a way to set these for the sync version?
```csharp
AMQP =
{
	MaxLinksPerSession = 1,
	MaxSessionsPerConnection = 1
}
```

And would that perhaps even help?

**Comment by Marvin-Brouwer** [comment]
Hi,

I no longer necessarily need this functionality.
I'll leave the issue open for the maintainers to either close or still answer.

**Comment by xinchen10** [comment]
Without the call-stacks of the threads it is hard to tell which configuration would help. I guess the application is doing a lot of sync calls by waiting on the tasks. In that case the number of threads depend on how many concurrent calls made by the application, instead of how the connections are created.
