### ISSUE TITLE
Amqp.Message is not serializable

### ISSUE THREAD

**Issue by ctetzlaff** [Azure/amqpnetlite#72]
Hello,
is there a way to serialize Amqp.Message objects to reach persistence? The Binary Formatter failed because the type isn't marked with the Serializable attribute. The XmlSerializer which doesn't care about the attribute failed too because Amqp.Types.Map implements IDictionary.

Maybe you can advise a different approach.

Kind regards

ctetzlaff

**Comment by robreeves** [comment]
@ctetzlaff How about using the serializer built into the library? You could do something like this.

            
            using (var stream = new FileStream("./file.dat", FileMode.Create))
            {
                var message = new Message("hello, world");
                var buffer = message.Encode();
                stream.Write(buffer.Buffer, 0, buffer.Buffer.Length);
            }

**Comment by ctetzlaff** [comment]
@robreeves That looks like a good alternative way! Thank you!
Maybe it could be a proposal to offer support for the buld-in serializers.

**Comment by robreeves** [comment]
@ctetzlaff Glad it works! 

For your proposed feature of adding support for built in .NET serializers @xinchen10 will have to weigh in. In my opinion, I would prefer not to add the XmlSerializer because it adds a reference to the System.Xml assembly and a goal of the library is to be as lightweight and portable as possible.
